[tool.poetry]
name = "langflow-trail"
version = "0.1.0"
description = ""
authors = ["Stephenworkplace <wenyeh8@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
